### ISSUE TITLE
web page error

### ISSUE THREAD

**Issue by serdarbayram01** [fhsieh/vysk-zabbix-dashboard#1]
hi , 

this script gives me this error on browser after installing, how can i resolve , do you have any idea ?

![zabbix_dash](https://user-images.githubusercontent.com/35360442/54207046-87081280-44ea-11e9-898f-5105a181a414.jpg)

`jquery.min.js:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.min.js:4
ajax @ jquery.min.js:4
makeAjaxCall @ zabbix.js:48
call @ zabbix.js:16
getApiVersion @ zabbix.js:25
(anonymous) @ app.js:78
j @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
J @ jquery.min.js:2
app.js:21 Uncaught TypeError: Cannot read property 'items' of undefined
    at Object.<anonymous> (app.js:21)
    at Function.each (jquery.min.js:2)
    at parseData (app.js:20)
    at HTMLDocument.<anonymous> (app.js:138)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.J (jquery.min.js:2)
(anonymous) @ app.js:21
each @ jquery.min.js:2
parseData @ app.js:20
(anonymous) @ app.js:138
j @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
J @ jquery.min.js:2
vue.js:10022 Download the Vue Devtools for a better development experience:
https://github.com/vuejs/vue-devtools`

**Comment by fhsieh** [comment]
The page appears that way because Vue is not loaded.

Check app.js, where Vue is initialized near the bottom using `var dash = new Vue({ el: '#dashboard', data: data });`. Most likely there is a Javascript error occurring before this call which stops Vue from being initialized.

Keep in mind, app.js expects a Zabbix instance. You will need Zabbix running and enable API access, and provide the connection settings in config.js under the `api: { ... }` object.

Unfortunately, I no longer maintain this project, but you may also want to check for other Zabbix API libraries, and also consider migrating this code to newer versions of Vue.

In general, your architecture should look like this:
- Zabbix API retrieves Zabbix host data and stores in JS data object (other library).
- Process JS data object into format that is easier for Vue to use (app.js `parseData` provides an example).
- Initialize Vue with the JS data object. Vue will take care of the rest.
